# 开发环境配置
# Copyright 2026 BudaOS Team

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/budaos?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: budaos

  redis:
    host: localhost
    port: 6379
    password: budaos

# MyBatis日志显示
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志级别
logging:
  level:
    root: DEBUG
    com.budaos: DEBUG

# 应用配置
com.budaos:
  captcha-enabled: true
  is-cors: true
  cors-url: "*"
